name: webapp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  fl_chart: ^0.10.1
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  intl: ^0.16.1
  share: ^0.6.5
  url_launcher: ^5.5.1
  package_info: ^0.4.3
  shared_preferences: ^0.5.10
  image_picker: ^0.6.7+7
  image_cropper: ^1.3.1
  cached_network_image: ^2.3.1

  provider: ^4.3.2+2
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf